### PR TITLE
Groups completion

### PR DESCRIPTION
**Pull request by danil-topc**
-add franchise, division checking and completing if rocket chat or nxc folder doesn't exist before user is added
-fix rocket channel search

### CODE REVIEW

**Comment by danil-topc** [comment]
Still investigating issue with folders, cause they stopped working as expected. Folders are created as before with right permissions for groups in nextcloud, but users cannot see them. 
It might be because of LDAP server clean-up. For example, Everybody team hadn't exist before I created it manually (TEAP will create it only when new user is created), so it caused issues, but something else is wrong with group folders.

@matejak btw, something wrong with test environment right now, cause it responds SERVER_DOWN after attempt to add object. However, in web interface it is ok.

**Comment by matejak** [comment]
This is a great piece of work - it will greatly improve usability and robustness when it is completed.
Just please try to specify what pieces are in WIP state, so testing and feedback on the PR can be more focused.

**Comment by danil-topc** [comment]
> Just please try to specify what pieces are in WIP state, so testing and feedback on the PR can be more focused.
The issue with nextcloud folders. It's not directly related to the PR with completion of groups, but still bug exists.

**Comment by danil-topc** [comment]
@matejak ok, it was because after edap instance clean-up, there was no team `Everybody`, and in nextcloud there were two folders "everybody" and "Everybody" with mixed permissions. 
May be we should add some script for start-up of TEAP instance to check if all required system groups/folders like Everybody group, Franchises, Divisions folders exist and have right permissions, fixing them or returning some log warning otherwise ? To avoid such issues.

**Comment by matejak** [comment]
Yes, go ahead with this in another PR. TEAP should have an on-demand sanity check + remediation, so when you request it, you get the message that some groups are inconsistent, and you are offered possibility to fix them.
Inconsistencies can happen due to various unforeseen complications, so TEAP should be somehow robust in this regard for sure.

**Comment by matejak** [comment]
Anyway, I am merging this, as it looks good, thank you for your work!

**Pull request merged**
