### PR TITLE
Franchises

### PR DESCRIPTION
**Pull request by danil-topc**

### CODE REVIEW

**Comment by matejak** [comment]
@danil-topc please rebase.
Anyway, is there anything you would like to that would explain the WIP status?

**Comment by danil-topc** [comment]
@matejak there is few issues left, but I think they can be done in another PR scope, because this one already massive.
1) It depends on https://github.com/EnterpriseyIntranet/teap/issues/14
2) The issue I described in rocket-chat, that nextcloud behavior is strange with some organizational units - it displays and find them by description, but not cn, especially it happens when there are multiple OU with same description. Didn't figure it out yet, because right now this bug only with franchises starting with `uk_`, it doesn't display their cn, but displays description with underscore number: `uk` is `Ukraine_3` right now, although ldap description is simply `Ukraine`. So this cause problems with group folder creation.
3) 
> Everybody should have read access to all countries folders

Could you please suggest the best way to do it? Is there a way to make folder public or should I add some kind of group 'everybody' ? 
4) Didn't separate adding user to team on front-end yet, because not clear where to do it on the interface - right now on user page there is way to add user to any `posixGroup`, but it should probably be divided for each organizational unit separately.

**Comment by danil-topc** [comment]
Also in next PRs it's better to add some asynchronous task queue (redis+celery will work perfectly), because when creating Division or Franchise right now, it takes few seconds to create all corresponding Teams, so user is waiting for response too long.

**Comment by matejak** [comment]
Thanks, merging! Concerning adding users to teams, it should be possible to do it during user creation, and later as well :-)

> Could you please suggest the best way to do it? Is there a way to make folder public or should I add some kind of group 'everybody' ?

This is actually a great idea. Please create a group for everybody, and add newly created users to it.

> Also in next PRs it's better to add some asynchronous task queue (redis+celery will work perfectly) ...

You are principally correct, but the problem you describe is not painful - adding a new franchise will be a relatively rare thing performed by the designated role. I would say that it is good to structure the implementation in a way which will allow to extend this easily, but don't do it now - it is not a pain point.

> ...  nextcloud behavior is strange with some organizational units ...

You have discovered a case not very well handled by Nextcloud itself. Again, TEAP can handle uniqueness of divisions/franchises on it's side, so this corner case does not occur.

**Pull request merged**
