### PR TITLE
Nextcloud user creation, multiple groups selection, notifications

### PR DESCRIPTION
**Pull request by danil-topc**
Features:
- New User page creation
- Multiple groups select for user
- Create new group with shared folder
- Deleting user, optionally purging empty groups
- Notifications for user about server response

Back-end:
- Add Group with folder api, to create group and shared folder in single request
- Groups api: search group by name
- Users api: create user with groups

Front-end:
- Integrate vue-multiselect, vue-notifications
- Add user creation page 
- Multiple groups select, create if doesn't exist, remove 

Notice: group with folder creation will work only if `groupfolders` app enabled in your nextcloud instance.

### CODE REVIEW

**Comment by matejak** [comment]
I have some UX-related comments - the selection of groups is a bit rough:

- nothing shows up until you start to write,
- what you type doesn't make any difference, and
- you can't enter custom groups.

You don't have to fix those issues (unless it's trivial), it is enough to comment them because of upcoming requirements changes.

Next, I see that you have tackled shared folder creation, but I don't know how it is supposed to work. Could you add that to the PR description or to the code itself, so it is indicated for the actual website users?

**Comment by danil-topc** [comment]
@matejak added description
> nothing shows up until you start to write
Fixed it, now initial data is loaded.

> what you type doesn't make any difference, and you can't enter custom groups.
I've added some fixes in last commit, but it was working before, it's strange. If group that you type not found, it will propose you to create this group below.

**Comment by matejak** [comment]
Good work, there are just two more outstanding issues:

- Now, the newly-created group (sub)folder doesn't belong to the group, so the user won't be able to see it.
- When you create e.g. a `country/Denmark` group folder, you have to be sure that `country` already exists, and is accessible for the group too. It has to be created and permissions have to be expanded if needed.

**Comment by danil-topc** [comment]
@matej thanks! 
Fixed issues with creating new group and it folders, subfolders with right permissions.

**Comment by matejak** [comment]
Works great, thanks you for the PR!

**Pull request merged**
